### ISSUE TITLE
Disconnected from DDP server.

### ISSUE THREAD

**Issue by Rechdan** [TheRealNate/meteor-react-native#12]
```tsx
// meteor
import Meteor from 'meteor-react-native';

// connect to meteor
Meteor.connect(process.env.NODE_ENV === 'development' ? 'ws://192.168.0.100:3000' : '');
```

I have this code and I'm getting the message `Disconnected from DDP server.`, what could be wrong?

Thanks!

**Comment by TheRealNate** [comment]
Hi @Rechdan.

I'm not sure if `process.env.NODE_ENV` works in React Native.

You can use the global constant `__DEV__`:
````
Meteor.connect(__DEV__ ? 'ws://192.168.0.100:3000' : '');
````

**Comment by Rechdan** [comment]
> Hi @Rechdan.
> 
> I'm not sure if `process.env.NODE_ENV` works in React Native.
> 
> You can use the global constant `__DEV__`:
> 
> ```
> Meteor.connect(__DEV__ ? 'ws://192.168.0.100:3000' : '');
> ```

I think it does work, because i did a `console.log` and it printed `development` and with this short if I got the websocket url, but still no connections to the Meteor server.

**Comment by TheRealNate** [comment]
Hi @Rechdan, could you try using this url: `ws://192.168.0.100:3000/websocket`? I think depending on how your app is hosted you may need to use the `/websocket` path to get the direct connection to the socket.

**Comment by Rechdan** [comment]
> Hi @Rechdan, could you try using this url: `ws://192.168.0.100:3000/websocket`? I think depending on how your app is hosted you may need to use the `/websocket` path to get the direct connection to the socket.

It seems to solve the problem, and actually that's weird because I did tried this before but with no success, now I got the `Connected to DDP server.`, finally! Hahaha

The code now:
```ts
// meteor
import Meteor from 'meteor-react-native';

// connect to meteor
Meteor.connect(process.env.NODE_ENV === 'development' ? 'ws://192.168.0.100:3000/websocket' : '');
```

Thanks for the help!

**Comment by TheRealNate** [comment]
Hi @Rechdan, glad to hear its working!
