### ISSUE TITLE
Help Wanted: TypeScript Declaration File

### ISSUE THREAD

**Issue by Rechdan** [TheRealNate/meteor-react-native#13]
For a near future release, would be possible to have a declaration file or the entire source of this project be converted to TypeScript?

**Comment by vforvasile** [comment]
Sorry about not opening a separate issue but I wanted to ask: Is this **Production** ready? Did anyone find issues in production? @TheRealNate

**Comment by TheRealNate** [comment]
Hey @Rechdan. We don't have any plans to convert the source to TypeScript, but I think a declaration file is a good idea. If anyone wants to open a PR that would be great!

**Comment by TheRealNate** [comment]
@vforvasile In the future, please open a separate issue in the future so as not to disrupt a conversation. This package is production ready. I myself am using this in one production app on both Android and iOS, and multiple development apps.

**Comment by TheRealNate** [comment]
Completed with PR #47. Will be released in `2.1.1` soon.

**Comment by TheRealNate** [comment]
2.1.1 has been released. Closing this issue.
