### ISSUE TITLE
Accounts.createUser does not immediately log user in

### ISSUE THREAD

**Issue by NickTheTurtle** [TheRealNate/meteor-react-native#22]
**Describe the bug**
Either Accounts.createUser does not immediately log user in, or Meteor.user() and Meteor.userId() does not get updated automatically when Accounts.createUser is successful

**To Reproduce**

App.js code:
```
class App extends React.Component {
  render() {
    return (
      <SafeAreaProvider>
        <IconRegistry icons={EvaIconsPack} />
        <ApplicationProvider {...eva} theme={eva.light}>
          {this.props.currentUser ? <ThisPage /> : <LoginPage />}
        </ApplicationProvider>
      </SafeAreaProvider>
    );
  }
}

export default withTracker(() => {
  return {
    currentUser: Meteor.user(),
  };
})(App);
```

Accounts.createUser code:
```
Accounts.createUser(
          {
            email: this.state.email,
            password: this.state.password,
          })
```

I can verify that a new user is indeed created in the database. However, upon successful creation of user, app does not automatically switch to <ThisPage /> but stays on <LoginPage />.

**Expected behavior**
Upon successful creation of user, app does automatically switch to <ThisPage />.

**Screenshots**
N/A

**Device (please complete the following information):**
 - Device: [e.g. iPhone 11]
 - OS: [e.g. iOS13.6]
 - React Native and MeteorRN versions: [e.g. 0.63.2, 2.0.8]

**Comment by TheRealNate** [comment]
Hi @NickTheTurtle 

Do you encounter any similar issues when logging in regularly? I'm still trying to reproduce the issue on my end.

Thanks!

**Comment by NickTheTurtle** [comment]
Hi, thanks for the quick reply. Logging in normally does not give any weird behaviors. I found this blog online that documented the same error: https://medium.com/differential/react-native-meteor-auth-with-email-username-and-password-d2085c732276. Seems like the bug existed for quite some time.

**Comment by TheRealNate** [comment]
One more thing to try, can you add a handler for the `Accounts.onLoginFailure` event:
````
Accounts.onLoginFailure(err => {
    console.error(err);
});
````

**Comment by NickTheTurtle** [comment]
I tried Accounts.onLoginFailure, and the error it logged was… "undefined", curiously. I attached the image below:

<img width="318" alt="image" src="https://user-images.githubusercontent.com/12247846/88351680-c7051980-cd1c-11ea-8550-693f74f902b3.png">

**Comment by TheRealNate** [comment]
Currently, `onLoginFailure` doesn't actually tell you the error, just calls the callback when there is one. However, this points to an error in the createUser call. Are you calling createUser with a callback?
````
Accounts.createUser({...}, err => {
    if(err) console.error(err);
});
````

The callback should have an error since onLoginFailure is being called. That should give you some more info.

**Comment by NickTheTurtle** [comment]
I can verify that a user is indeed created by checking with "meteor mongo". Also, the error callback in createUser is not called as I set it to display pop up boxes if errors occurred (and the pop up boxes do appear when, say there is already an account in the system).

**Comment by TheRealNate** [comment]
Thats really strange. When createUser is called, whatever error/result it receives is passed directly to `_handleLoginCallback` which in turn triggers `onLoginFailure` if there was an error, but the same error should have been passed to your callback.

If you would be willing to make some changes to your local version of the package, you can make a change to:
````
node_modules/@meteorrn/core/src/user/Accounts.js
````

Inside the `createUser` method, you can log the error and result received to confirm that there is no error and that a token is being returned.

If you'd prefer not to make these changes, I have a release planned for tomorrow that implements some deeper debugging.

**Comment by NickTheTurtle** [comment]
Ok, so after putting some console messages in Accounts.js, I found out that every function that's supposed to be called is called, and no err was always undefined. However, after making the changes to Accounts.js, the app reloaded on the second time and the user got logged in. This did not happen when changing my ReactNative files, curiously. This makes me think that the app did successfully log the user in after account creation, but the notification did not get propagated and Meteor.user() did not change.

**Comment by TheRealNate** [comment]
Could you try adding a timeout and logging `Meteor.user()` and `Meteor._userIdSaved` (note that _userIdSaved is a string value not a function)? Once the login callback is handled, `_userIdSaved` is immediately set, but its possible that for some reason the user object isn't being received from the server.

**Comment by NickTheTurtle** [comment]
I'm not sure what changed, but now creating an account logs the user in.

**Comment by NickTheTurtle** [comment]
It logs `null` and `undefined`, respectively.

**Comment by TheRealNate** [comment]
So, when `_handleLoginCallback` is called _userIdSaved should be immediately set (unless there is an err). When you put your console messages, did you confirm that _handleLoginCallback was not receiving an err object? If so, something else is happening, possibly related to your other issue (how the functions are being bound to `this`).

**Comment by NickTheTurtle** [comment]
Yeah, no error occurred. Also, I have a logging in indicator that fires when the user is logging in but doesn't upon account creation. I was able to verify that Users._startLoggingIn was called though. If I manually call Meteor._startLoggingIn, everything works.

**Comment by copleykj** [comment]
A reproduction of this and #20 might be helpful if possible.

**Comment by TheRealNate** [comment]
Hey @NickTheTurtle, any chance this issue could be related to #21, where this wasn't being bound correctly?

**Comment by TheRealNate** [comment]
Hi @NickTheTurtle, just following up to see if this issue is resolved?

**Comment by NickTheTurtle** [comment]
I don't think it's a "this" issue since I'm calling Accounts.createUser in a class method.

**Comment by TheRealNate** [comment]
Hi @NickTheTurtle, could you see if the issue is still happenning with release `2.0.13`?

**Comment by TheRealNate** [comment]
Hi @NickTheTurtle, any updates on this?

**Comment by TheRealNate** [comment]
Closing this as it is stale. Feel free to re open if the issue persists.
