### ISSUE TITLE
Collections.observe problems

### ISSUE THREAD

**Issue by NickTheTurtle** [TheRealNate/meteor-react-native#23]
**Describe the bug**
I'm calling Collections.observe to track added documents to a collection in withTracker. In the same withTracker component, I call subscribe to the same collection and do some other querying. For each document I added, the function I set in Collections.observe is called up to ~20 times on the same added document. In addition, when I navigate away from the page (so withTracker component should be unmounted), it seems like the function in Collections.observe is still called whenever a document is added.

**Expected behavior**
The function is Collections.observe should only be called once on each added document. It should stop being called once withTracker is destroyed, similar to subscribe.

**Device (please complete the following information):**
 - Device: [e.g. iPhone 11]
 - OS: [e.g. iOS 13.6]
 - React Native and MeteorRN versions: [e.g. 0.63.1, 2.0.8]

**Comment by TheRealNate** [comment]
Hi @NickTheTurtle. I think the observer being deleted when withTracker is destroyed may be a feature request, could you create a separate issue?

Regarding the callback being called multiple times, is it possible that the subscription is being destroyed and recreated? The current observer implementation will run the callback anytime it receives the added message from the server through the websocket. Maybe we need to cache the documents added has already been called for?

**Comment by TheRealNate** [comment]
Hi @NickTheTurtle, any updates on this?

**Comment by TheRealNate** [comment]
Closing this issue as it is stale. Feel free to reopen this if the issue is still persisting
