### ISSUE TITLE
node_modules/@meteorrn/core/src/user/User.js: Identifier 'call' has already been declared (5:8)

### ISSUE THREAD

**Issue by zsliu** [TheRealNate/meteor-react-native#24]
Following the readme to run a simple react native app on android simulator, the following errors shown

meteorclient/node_modules/@meteorrn/core/src/user/User.js: Identifier 'call' has already been declared (5:8)

  3 | import call from '../Call';
  4 | import Mongo from '../Mongo';
> 5 | import {call, connect, isVerbose} from '../Meteor.js';
    |         ^
  6 |
  7 | const TOKEN_KEY = 'reactnativemeteor_usertoken';
  8 | const Users = new Mongo.Collection("users");

**To Reproduce**

react-native run-anroid on the example shown in the readme

**Comment by xwz** [comment]
This is a basic syntax error. There are currently no tests at all for this package :(

**Comment by TheRealNate** [comment]
This issue should be fixed in release `2.0.13`
