### ISSUE TITLE
Moving Things Forward

### ISSUE THREAD

**Issue by copleykj** [TheRealNate/meteor-react-native#28]
Hello Nathaniel,

First off I'd like to introduce myself. My name is Kelly Copley. I'm one of the founders of Meteor Community Packages and the author of the packages published under the Socialize namespace both on Atmosphere and NPM. I've been working with Meteor since it's 0.5 release, and I've been a die hard fan ever since.

A couple years ago, as part of my efforts to port [Socialize](https://atmospherejs.com/socialize) packages to NPM for use with RN, and due to the abandonment of the `react-native-meteor` package, I forked the package as `@socialize/react-native-meteor`, made several much needed changes, and have been maintaining it since.

As part of recent updates I made changes that allowed the package to be used in environments outside RN. Because of this I started thinking that the individual pieces contained within the package didn't make sense together, and that they should be spit so that pieces that were React specific could be used with as such, the core part could be used in any environment supporting a JS runtime, and the accounts-password functionality, as well as other functionality could be provided as additional packages. This would be very similar to how Meteor itself is already structured, and I believe it could open up a whole host of possibilities to use Meteor in other tool chains.

I've recently spoken with Filipe Nevola about this idea. He liked the idea and suggested that I seek your cooperation since you've been putting effort into Meteor usage in React Native.

Currently I've created a new repository under the Meteor Community Packages org and started a planning issue thread at Meteor-Community-Packages/meteor-api#1.

I'd like to invite you, and anyone else interested, to join in the planning and development of this set of packages to make the Meteor ecosystem stronger and foster wider adoption.

Thanks so much for your time,
Kelly Copley

**Comment by TheRealNate** [comment]
Hi Kelly,

Thanks for reaching out! This undertaking sounds really exciting. I'd love to help if I can.

Do you have a channel setup for this project on the Meteor slack where we (and anybody else interested) can discuss next steps?

**Comment by copleykj** [comment]
I currently do not, but that sounds like a good idea and I'm happy to create one.
