### ISSUE TITLE
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

### ISSUE THREAD

**Issue by imhazige** [TheRealNate/meteor-react-native#33]
**Describe the bug**
After create a React native app with npx react-native init, then in the App.js import Meteor from '@meteorrn/core';
then the simulator show blank screen. and show the error. 

**To Reproduce**
1. Just import Meteor
2. See error

**Expected behavior**
App able to start

**Screenshots**
Debugger worker loaded runtime on port 12686
Require cycle: node_modules/@meteorrn/core/src/Meteor.js -> node_modules/@meteorrn/core/src/user/User.js -> node_modules/@meteorrn/core/src/Meteor.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

**Comment by TheRealNate** [comment]
Hi @imhazige, the message you are seeing is a low-severity warning. It will only appear in the bundler, and does not prevent the app from loading. Is it possible there is another issue preventing your app from loading?

**Comment by imhazige** [comment]
ok, I will create a more pure view.

now when I uncomment the import Meteor ....,(no other meteor code) the problem happen, UI not shown. when comment it, the problem disappears and UI shown.

**Comment by imhazige** [comment]
I have reproduce the problem with a plain project and only have meteor dependencies https://github.com/imhazige/react-native-meteor-blank-screen-problem

**Comment by imhazige** [comment]
https://github.com/imhazige/react-native-meteor-blank-screen-problem/blob/master/App.js#L27 uncomment this line will make a blank screen

**Comment by imhazige** [comment]
after install @react-native-community/async-storage which is missing and run npx pod-install ios, still blank.

**Comment by TheRealNate** [comment]
Are you seeing any other errors in the console? The "require cycle" error is likely not the cause of your issue.

**Comment by imhazige** [comment]
could you try https://github.com/imhazige/react-native-meteor-blank-screen-problem/blob/master/App.js.


no other error.

**Comment by TheRealNate** [comment]
Hi @imhazige, a few questions to diagnose this further:

- What kind of device are you using (iOS/Android and Simulator/Real (if real, what model))? 
- Are you building for debug or release?

From what you have told me it sounds like something is causing the whole React tree to crash, but that would usually produce some sort of error message. If you are bundling for production however, it may not appear unless you implement try/catch or an error boundary.

**Comment by lemonbusadmin** [comment]
I am using simulator.

https://github.com/imhazige/react-native-meteor-blank-screen-problem

are you able to run?

**Comment by TheRealNate** [comment]
@lemonbusadmin are you having this issue as well?

**Comment by imhazige** [comment]
I am using simulator.

https://github.com/imhazige/react-native-meteor-blank-screen-problem

are you able to run?

**Comment by TheRealNate** [comment]
Hi @imhazige, could you try running the latest beta release and see if that fixes your issue?

**Comment by imhazige** [comment]
Hi, @TheRealNate 

same behavior.

![image](https://user-images.githubusercontent.com/4122902/93412277-70a4f900-f8cf-11ea-8192-2928b1519e8b.png)

  "dependencies": {
    "@meteorrn/core": "^2.1.0-beta1",
    "@react-native-community/async-storage": "^1.11.0",
    "@react-native-community/netinfo": "^5.9.6",
    "react": "16.13.1",
    "react-native": "0.63.2"
  },

**Comment by TheRealNate** [comment]
Hi @imhazige, I'm going to correct the require cycle for the `2.1.0` release. Hopefully this should correct your issue. I will keep you posted.

**Comment by TheRealNate** [comment]
Hi @imhazige, the `2.1.0` release candidate has been published, and it eliminates the require cycle. If you'd like, you can try it now with `npm install --save @meteorrn/core@2.1.0-rc1`

**Comment by imhazige** [comment]
Hi @TheRealNate,

The warning disappear now. Well done, thank you.

About the blank screen problem, I found if I stop debug, it will show, if start debug, it will be blank again. 

So I think it should not be related to this library.

Anyway the thank you for enhanced it. Cheers!
