### ISSUE TITLE
async storage from react-native-community deprecated and moved 

### ISSUE THREAD

**Issue by OlivierJM** [TheRealNate/meteor-react-native#39]
The package referred was moved to another repository and namespace as well. 
https://github.com/TheRealNate/meteor-react-native/blob/f2ebc8f7780c7f9821a59f0676ca4c4207b531af/package.json#L48

I suggest we point to the right package and the correct version.
ref: https://www.npmjs.com/package/@react-native-community/async-storage

**Comment by OlivierJM** [comment]
I would love to work on this, If I have a go ahead. 
cc: @TheRealNate

**Comment by TheRealNate** [comment]
@OlivierJM, sorry about the delayed reply. If you could add a PR for this that would be great, thanks!

**Comment by OlivierJM** [comment]
Thanks a lot, I will start working on it.
