### ISSUE TITLE
Remove reference to UNSAFE_componentWillMount

### ISSUE THREAD

**Issue by TheRealNate** [TheRealNate/meteor-react-native#4]
`componentWillMount` has been deprecated and will be removed in React 17.

/src/components/ReactMeteorData.js#L8

**Comment by PolarisWT** [comment]
I would think that changing this to a `componentDidMount()` would work.  I have not noticed any side-effects locally with this updated.

**Comment by TheRealNate** [comment]
After doing some more reading on docs, its possible that moving the code into the constructor method may mimic the behavior of `componentWillMount` better.

**Comment by PolarisWT** [comment]
I thought about that too, but found no loss of performance or issues yet - although my case is very limited in use so far 🤞 .  I am all for better solutions, but struggling to find good ways to test these in a meaningful way.  

How are you going about testing?   I spent a little time spooling up mocha that was from the `react-native-meteor` repo, but decided that was a bigger project...

**Comment by TheRealNate** [comment]
PR #10 has been merged in beta release `2.1.0-beta1`

**Comment by TheRealNate** [comment]
This has been fixed in `2.1.0`
