### ISSUE TITLE
Getting error while using useTracker hook

### ISSUE THREAD

**Issue by rajtejani** [TheRealNate/meteor-react-native#60]
**Describe the bug**
I have installed 2.1.0 and tried to use **useTracker** hook but it gives me an error that _core.useTracker is not a. function. I am trying to use this hook inside the function component.

**Screenshots**
![simulator_screenshot_11FD8C81-CF09-4EBE-A02B-F78544CD66F6](https://user-images.githubusercontent.com/49932204/114502189-02e46400-9c49-11eb-9b5b-c33bf750478f.png)

**Device (please complete the following information):**
 - React Native and MeteorRN versions: [e.g. 0.63.0, 2.1.0]

**Comment by TheRealNate** [comment]
Hi @rajtejani, how are you defining the `useTracker` variable? useTracker is a property of Meteor, so needs to be used like this:

````
import Meteor from '@meteorrn.core';

...

Meteor.useTracker(() => {
})
```` 

or this:

````
import Meteor from '@meteorrn.core';
const { useTracker } = Meteor;

...

useTracker(() => {
})
```` 

Are you using the second option?

**Comment by rajtejani** [comment]
Thanks @TheRealNate . I was actually importing like this 😅
`import {useTracker} from '@meteorrn/core'.`

Your both way is working fine.
Thanks for the help again.
