### ISSUE TITLE
Subscription on mobile are not stable as Web

### ISSUE THREAD

**Issue by rajtejani** [TheRealNate/meteor-react-native#73]
**Describe the bug**
I am facing issues where subscription made in mobile devices with this package is not stable as compared to Web. I made console.log to mobile and web and when checked all logs, I found out that on the web, the subscription doesn't change its status between "ready" and "not ready" wherein mobile it toggles status between "ready" and "not ready" continuously.

**Screenshots**
![Screenshot 2021-08-23 at 9 49 53 AM](https://user-images.githubusercontent.com/49932204/130390016-3e201600-2326-4334-9dd7-75a07796eab0.png)
![Screenshot 2021-08-23 at 9 48 33 AM](https://user-images.githubusercontent.com/49932204/130390093-88bf963d-4e4c-4b25-a35d-8c85ac0c1b2a.png)

**Comment by TheRealNate** [comment]
Hi @rajtejani,

To help figure out the issue could you answer the following:

1. Are you using this in a mobile app or on `react-native-web` or something similar?
2. Could you please provide an example of how you're subscribing with as much context as possible? 

Thanks!

**Comment by TheRealNate** [comment]
Closing this issue due to no response - feel free to reopen
