### ISSUE TITLE
Is it possible to get the Meteor.loginToken value?

### ISSUE THREAD

**Issue by ma10as** [TheRealNate/meteor-react-native#84]
I will like to know if they are any options to get the loginToken, so I can pass this token to the Apollo client to resolve the User in Apollo Query or Mutation?

Thank's for your help;

**Comment by TheRealNate** [comment]
Hi @ma10as, 

You can use this code to access the token:

````
await Meteor.packageInterface().AsyncStorage.getItem("reactnativemeteor_usertoken")
````

Marking this question as closed. Fee free to reopen if you have any further questions.
